"""Provider protocols and normalized adapter contracts."""

from debate_api.providers.model import (
    FakeModelOutcome,
    FakeModelStep,
    ModelErrorCategory,
    ModelIdentity,
    ModelProvider,
    ModelProviderError,
    ModelRequest,
    ModelResponse,
    ModelUsage,
    ProgrammableFakeModelProvider,
    validate_structured_output,
)
from debate_api.providers.openai_compatible import (
    DEFAULT_OLLAMA_BASE_URL,
    DEFAULT_OLLAMA_MODEL,
    DEFAULT_OPENAI_BASE_URL,
    DEFAULT_QWEN_MODEL_REVISION,
    OpenAICompatibleModelProvider,
)
from debate_api.providers.research import (
    DnsResolver,
    DocumentExtractor,
    DocumentStatus,
    DocumentType,
    ExtractedDocument,
    ExtractorIdentity,
    FetchLimits,
    FetchProvider,
    SafeDocumentExtractor,
    SafeDocumentFetcher,
    SafeFetchException,
    SystemDnsResolver,
)
from debate_api.providers.research_runtime import (
    ManagedResearchProvider,
    ResearchProviderRuntime,
    build_research_provider,
)
from debate_api.providers.search import (
    SearchHit,
    SearchProvider,
    SearchProviderMetadata,
    SearchQuery,
    SearchResponse,
    TavilyErrorCategory,
    TavilySearchError,
    TavilySearchProvider,
    normalize_tavily_response,
)

__all__ = [
    "FakeModelOutcome",
    "FakeModelStep",
    "ModelErrorCategory",
    "ModelIdentity",
    "ModelProvider",
    "ModelProviderError",
    "ModelRequest",
    "ModelResponse",
    "ModelUsage",
    "ProgrammableFakeModelProvider",
    "validate_structured_output",
    "DEFAULT_OPENAI_BASE_URL",
    "DEFAULT_OLLAMA_BASE_URL",
    "DEFAULT_OLLAMA_MODEL",
    "DEFAULT_QWEN_MODEL_REVISION",
    "OpenAICompatibleModelProvider",
    "DocumentStatus",
    "DocumentType",
    "DocumentExtractor",
    "DnsResolver",
    "ExtractedDocument",
    "ExtractorIdentity",
    "FetchProvider",
    "FetchLimits",
    "SafeDocumentExtractor",
    "SafeDocumentFetcher",
    "SafeFetchException",
    "SystemDnsResolver",
    "SearchHit",
    "SearchProvider",
    "SearchProviderMetadata",
    "SearchQuery",
    "SearchResponse",
    "TavilyErrorCategory",
    "TavilySearchError",
    "TavilySearchProvider",
    "normalize_tavily_response",
    "ManagedResearchProvider",
    "ResearchProviderRuntime",
    "build_research_provider",
]
